### ISSUE TITLE
[Question] What does the option EnableMaskLurkingMechanic do?

### ISSUE THREAD

**Issue by haroelim** [OE100/PossessedMask#16]
What does the option EnableMaskLurkingMechanic do? By default it is set to true.

**Comment by OE100** [comment]
it honestly was a feature I was testing (so it's not doing anything in the release) but decided it was too unrelated to the mod, I'm working on making it it's own mod since I'm happy with the state of Possessed Masks right now.

The mechanic was supposed to make a dropped mask become an enemy and lurk around you (running away if you looked at it and coming back), after a while around you it would prime itself (return to item form) and the next time someone picks it up it would immediately attach to him.
