### ISSUE TITLE
1.1.2 bug

### ISSUE THREAD

**Issue by trasshtalker** [OE100/PossessedMask#5]
mask value is not changing in config, config says minimum 100, i see masks only 40-50

**Comment by trasshtalker** [comment]
tried with only this mod installed thinking maybe conflicts with other mods, nope

**Comment by OE100** [comment]
it's affected by level multipliers, the config lets you set the base item value but each level has a multiplier for those values, some of the earlier levels have a multiplier of less than 0.5 I think, so it makes sense.

**Comment by trasshtalker** [comment]
by level u mean moons or what, on 1.1.1 there wasnt such a problem, i checked on titan if u mean moons

**Comment by trasshtalker** [comment]
yeah man its literally broked the config value of mask from 1.1.0 version, i tested on 1.0.1.0 version everything works perfect, but installing 1.1.0 its broken again, why u closed issue idk, u can chat me in discord if u want proofs

**Comment by OE100** [comment]
that's a bit confusing, but it's because in earlier versions I prevented the default game value multiplier from affecting the masks, the multiplier is 0.4 or something like that, just account for it when setting the value in the config.

I took it into account because it might've broken someone elses balancing mod.

**Comment by trasshtalker** [comment]
but u gonna fix it to how it was before? if i set 100-150 value its gonna be 100-150 quota mask without multipliers
